package command

// MkDirPerm defines default permissions for created directories
const MkDirPerm = 0755

// MkFilePerm defines default permissions for created files
const MkFilePerm = 0644

const FormatEnv = "env"
const FormatJson = "json"
const FormatJsonCompact = "json_compact"
const FormatBatch = "batch"

var AllowedInputFormats = []string{FormatEnv, FormatJson, FormatBatch}
var AllowedDumpFormats = []string{FormatEnv, FormatJson, FormatJsonCompact}

const ExampleEnv = `
# This is an example environment variable configuration file.
# Change it to fit your needs. Comments and quotes are supported.
FOO=bar
NUMBER=55
GREET="Hello, world!"
BOOL=true
SprigURL=https://masterminds.github.io/sprig/	
GoURL"="https://pkg.go.dev/text/template
`

// ExampleJson is an example JSON configuration file.
const ExampleJson = `{
  "debug": true,
  "foo": "bar",
  "NUMBER": 42,
  "nested": {"baz": "faz"},
  "SprigURL": "https://masterminds.github.io/sprig/",	
  "GoURL": "https://pkg.go.dev/text/template"	
}
`

// ExampleBatchJson is an example batch JSON configuration file.
const ExampleBatchJson = `{
  "items": [
    {
      "info": "This template will combine defaults with other values.",
      "target": "rendered.txt",
      "template": "./templates/custom.tpl",
      "variables": {
        "FOO": "custom",
        "extra": "extra value"
      }
    },
    {
	  "info": "Will use all defaults to render the template.",
      "target": "with_defaults.txt"
    }
  ],
  "defaults": {
    "info": "This section defines default values to be used in the \"items\" section.",
    "template": "./templates/template.txt.tpl",
    "variables": {
      "FOO": "bar",
      "NUMBER": 42,
      "nested": {"baz": "faz"},
      "SprigURL": "https://masterminds.github.io/sprig/",	
      "GoURL": "https://pkg.go.dev/text/template"
    }
  }
}
`

// ExampleTemplate is an example template
const ExampleTemplate = `
This is an example of template for templar to use
{{ .GREET }} and {{ .BOOL }}.
{{ if .debug -}}
Debug is enabled
{{ end }}
My lucky number is {{ .NUMBER }}.
Directly read your ENV variables with disregard to options and overrides: your username is: {{ env "USER" }}.
See {{ .SprigURL }} and {{ .GoURL }} for more information on usage.

JSON has nested parameter {{ default "N/A" .nested }}.
`

// ExampleCustomTemplate is an example customised template
const ExampleCustomTemplate = `
# Generated by Templar at {{ now | date "2006-01-02 15:04:05" }}
This is an example of customised template for templar to use
{{ .GREET }} and {{ .BOOL }}.

My lucky number is {{ .NUMBER }}.
See {{ .SprigURL }} and {{ .GoURL }} for more information on usage.

JSON has nested parameter {{ default "N/A" .nested }}.
`
